FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY  package.json pnpm-lock.yaml* ./

RUN pnpm install --frozen-lockfile

COPY  . .

RUN pnpm build



FROM node:20-alpine

WORKDIR /app

RUN npm i -g pnpm
COPY --from=builder /app/package.json /app/pnpm-lock.yaml* ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
EXPOSE 3131
CMD [ "node", "dist/index.js" ]